# Generated by Django 3.1.3 on 2020-11-24 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('baslik', models.CharField(max_length=50)),
                ('resim', models.ImageField(upload_to='')),
                ('durum', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tarih', models.DateTimeField()),
                ('baslik', models.CharField(max_length=50)),
                ('icerik', models.CharField(max_length=50)),
                ('durum', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Etkinlik',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('baslik', models.CharField(max_length=50)),
                ('icerik', models.CharField(max_length=50)),
                ('resim', models.ImageField(upload_to='')),
                ('tarih', models.DateTimeField()),
                ('durum', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('baslik', models.CharField(max_length=50, verbose_name='Title')),
                ('icerik', models.CharField(max_length=50)),
                ('alan', models.CharField(max_length=50)),
                ('hedef', models.URLField()),
                ('durum', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kategori', models.CharField(max_length=50)),
                ('unvan', models.CharField(max_length=50)),
                ('ad_soyad', models.CharField(max_length=50)),
                ('resim', models.ImageField(upload_to='')),
                ('CV', models.CharField(max_length=1000)),
                ('durum', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yonetici',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ad_soyad', models.CharField(max_length=50)),
                ('kullanici_ad_soyad', models.CharField(max_length=50)),
                ('kullanici_adi', models.CharField(max_length=50)),
                ('kullanici_sifre', models.CharField(max_length=50)),
                ('kullanici_yetki', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AltSayfa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('baslik', models.CharField(max_length=50)),
                ('icerik', models.CharField(max_length=50)),
                ('alan', models.CharField(max_length=50)),
                ('hedef', models.URLField()),
                ('durum', models.BooleanField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.menu')),
            ],
        ),
    ]
