# Generated by Django 3.1.3 on 2020-12-10 20:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='CV',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='personel',
            name='resim',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
