# Generated by Django 3.1.3 on 2020-12-11 17:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20201210_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yonetici',
            name='kullanici_ad_soyad',
        ),
        migrations.AlterField(
            model_name='altsayfa',
            name='baslik',
            field=models.CharField(max_length=50, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='altsayfa',
            name='durum',
            field=models.BooleanField(blank=True, null=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='baslik',
            field=models.CharField(max_length=50, verbose_name='Baaşlık'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='durum',
            field=models.BooleanField(blank=True, null=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='baslik',
            field=models.CharField(max_length=50, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='durum',
            field=models.BooleanField(blank=True, null=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='etkinlik',
            name='baslik',
            field=models.CharField(max_length=50, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='etkinlik',
            name='durum',
            field=models.BooleanField(blank=True, null=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='baslik',
            field=models.CharField(max_length=50, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='durum',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='CV',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name='Öz Geçmiş'),
        ),
        migrations.AlterField(
            model_name='personel',
            name='ad_soyad',
            field=models.CharField(max_length=50, verbose_name='Adı Soyadı'),
        ),
        migrations.AlterField(
            model_name='personel',
            name='durum',
            field=models.BooleanField(blank=True, null=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='personel',
            name='resim',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='personel',
            name='unvan',
            field=models.CharField(max_length=50, verbose_name='abc'),
        ),
        migrations.AlterField(
            model_name='yonetici',
            name='ad_soyad',
            field=models.CharField(max_length=50, verbose_name='Adı Soyadı'),
        ),
        migrations.AlterField(
            model_name='yonetici',
            name='kullanici_adi',
            field=models.CharField(max_length=50, verbose_name='Kullanıcı Adı'),
        ),
        migrations.AlterField(
            model_name='yonetici',
            name='kullanici_sifre',
            field=models.CharField(max_length=50, verbose_name='Kullanıcı Şifre'),
        ),
        migrations.AlterField(
            model_name='yonetici',
            name='kullanici_yetki',
            field=models.CharField(max_length=50, verbose_name='Kullanıcı Yetki'),
        ),
    ]
