# Generated by Django 3.1.3 on 2020-12-12 09:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20201211_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='alan',
        ),
        migrations.AlterField(
            model_name='altsayfa',
            name='alan',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='altsayfa',
            name='baslik',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='altsayfa',
            name='icerik',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='içerik'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='baslik',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='baslik',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='icerik',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='içerik'),
        ),
        migrations.AlterField(
            model_name='etkinlik',
            name='baslik',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='etkinlik',
            name='icerik',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='içerik'),
        ),
        migrations.AlterField(
            model_name='etkinlik',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='menu',
            name='baslik',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='durum',
            field=models.BooleanField(blank=True, null=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icerik',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='içerik'),
        ),
        migrations.AlterField(
            model_name='personel',
            name='CV',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Öz Geçmiş'),
        ),
    ]
