# Generated by Django 3.1.3 on 2020-12-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20201212_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='duyuru',
            name='dosya',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='dosya',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
